import type { ProtocolDef } from "./types";

/** Claim-tiered ordinary-wellness protocols mirrored from bios/packs (UI catalog). */
export const PROTOCOLS: ProtocolDef[] = [
  {
    id: "proto_morning_light_10m",
    short: "morning-light-10m",
    title: "Morning outdoor light — 10 minutes",
    pack: "circadian",
    hypothesis:
      "Brief outdoor light within an hour of waking improves morning alertness and bedtime ease over 14 days.",
    summary: "Ten minutes outside after waking. Overcast counts. Never stare at the sun.",
    steps: [
      "Within ~60 minutes of waking, step outdoors",
      "Stay about 10 minutes",
      "Log alertness 1–10 and evening sleepiness",
    ],
    evidence_tier: "expert_consensus",
    anchor: "upon_waking",
    duration_days: 14,
    contraindications: [
      "Photosensitizing medication or clinician light restriction",
      "Active eye injury or post-eye-surgery limits",
    ],
  },
  {
    id: "proto_caffeine_cutoff_8h",
    short: "caffeine-cutoff-8h",
    title: "Caffeine cutoff — 8 hours before sleep",
    pack: "circadian",
    hypothesis: "Stopping caffeine ~8 hours before target bedtime improves subjective sleep quality.",
    summary: "Pick a cutoff clock. After that, water or non-caffeine drinks only.",
    steps: [
      "Choose target bedtime",
      "Set cutoff = bedtime − 8 hours",
      "Log any slips without judgment",
    ],
    evidence_tier: "cohort",
    anchor: "evening",
    duration_days: 14,
    contraindications: ["Clinician-directed caffeine use", "Rigid food rules during ED care"],
  },
  {
    id: "proto_box_breath_5m",
    short: "box-breath-5m",
    title: "Box breathing — 5 minutes",
    pack: "breath",
    hypothesis: "Gentle 4-4-4-4 breathing once daily reduces subjective stress without dizziness.",
    summary: "Easy box breath. Stop if dizzy, chest pain, or panic rises.",
    steps: [
      "Sit upright",
      "Inhale 4 · hold 4 · exhale 4 · hold 4",
      "Keep effort soft for ~5 minutes",
      "Score stress before/after 1–10",
    ],
    evidence_tier: "expert_consensus",
    anchor: "as_needed",
    duration_days: 14,
    contraindications: ["Unstable heart/lung disease without clearance", "Active medical panic"],
  },
  {
    id: "proto_meal_photo_log_7d",
    short: "meal-photo-log-7d",
    title: "Meal photo log — 7 days",
    pack: "nutrition",
    hypothesis: "Photographing meals increases awareness of timing and protein-containing meals.",
    summary: "Photo + 20-second log. Stop if logging triggers disordered eating thoughts.",
    steps: [
      "Photograph main meals",
      "Note hunger 1–10",
      "Mark protein-containing food yes/no",
    ],
    evidence_tier: "expert_consensus",
    anchor: "with_meals",
    duration_days: 7,
    contraindications: ["Active ED treatment restricting food logging"],
  },
  {
    id: "proto_evening_herbal_tea_ritual",
    short: "evening-herbal-tea-ritual",
    title: "Evening non-caffeine tea ritual",
    pack: "tea",
    hypothesis: "A consistent non-caffeine evening tea ritual eases wind-down over 14 days.",
    summary: "One ordinary cup of a culinary tea you already tolerate. Not botanical medicine dosing.",
    steps: [
      "Choose a non-caffeine culinary tea you already use safely",
      "Brew one ordinary cup",
      "Sit away from bright screens if possible",
      "Log wind-down ease 1–10",
    ],
    evidence_tier: "expert_consensus",
    anchor: "pre_sleep",
    duration_days: 14,
    contraindications: ["Known herb allergy", "Clinician/pharmacist avoidance advice"],
  },
];

export const PHASES = [
  {
    id: "upon_waking",
    label: "Wake light",
    hour: 7,
    color: "#e0b56a",
    hint: "Outdoor light protocol window",
  },
  {
    id: "midday",
    label: "Midday meal",
    hour: 12.5,
    color: "#6dcaa0",
    hint: "Meal photo + protein awareness",
  },
  {
    id: "as_needed",
    label: "Breath",
    hour: 16,
    color: "#3caa74",
    hint: "Box breath when stress rises",
  },
  {
    id: "pre_sleep",
    label: "Wind-down tea",
    hour: 21,
    color: "#c27a5a",
    hint: "Non-caffeine culinary tea ritual",
  },
] as const;
